### PR TITLE
Fixed regression running migrations through cli

### LINKED ISSUE #1197: migrate fails PostgreSQL 9.5
Ever since I upgraded to PostgreSQL 9.5, whenever I try to migrate, it fails with the following message (added the DEBUG info):

I'm using knex 0.10.0-rc1 CLI. I've tried the exact same migration code on an existing different project that works with a PostgreSQL 9.4 database and it succeeds. But just to check, this is the code used:

```
exports.up = function(knex, Promise) {
  return Promise.all([
  	knex.schema.createTable('artists', function (table) {
  		table.increments('ID');
  		table.string('name');
  	}),
  	knex.schema.createTable('albums', function (table) {
  		table.increments('ID');
  		table.string('title').notNullable();
  		table.integer('artist_ID').references('ID').inTable('artists').notNullable();
  		table.string('release_date').notNullable();
  		table.text('description').notNullable();
  		table.string('spotify_link');
  		table.string('playstore_link');
  		table.string('rym_link');
  		table.string('album_art').notNullable();
  	}),
  	knex.schema.createTable('lists', function (table) {
  		table.increments('ID');
  		table.string('title');
  		table.string('category');
  	}),
  	knex.schema.createTable('best_videos_songs', function (table) {
  		table.increments('ID');
  		table.integer('artist_ID').references('ID').inTable('artists').notNullable();
  		table.string('title').notNullable();
  		table.string('rank').notNullable(); // 0 = honorary
  		table.string('youtube_link').notNullable();
  		table.integer('type').notNullable(); // 0 = video, 1 = song
  		table.string('year').notNullable();
  	}),
  	knex.schema.createTable('best_albums', function (table) {
  		table.increments('ID');
  		table.integer('album_ID').references('ID').inTable('albums').notNullable();
  		table.string('rank').notNullable();
  		table.string('year').notNullable();
  	})
  ]).then(function () {
  		return knex.schema.createTable('lists_albums', function (table) {
  			table.integer('list_ID').references('ID').inTable('lists').notNullable();
  			table.integer('album_ID').references('ID').inTable('albums').notNullable();
  			table.primary(['list_ID', 'album_ID']);
  		});
  	});
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTable('lists_albums')
  	.then(function () {
  		return Promise.all([
  			knex.schema.dropTable('lists'),
  			knex.schema.dropTable('best_videos_songs'),
  			knex.schema.dropTable('best_albums'),
  			knex.schema.dropTable('albums'),
  			knex.schema.dropTable('artists')
  		]);
  	});
};
```

Could this be an issue on my end, or is this because of PostgreSQL 9.5?

### PR DESCRIPTION
**Pull request by elhigu**
Fixes  #1197

### CODE REVIEW

File: src/migrate/index.js [hunk 1]
```diff
@@ -196,7 +196,7 @@ export default class Migrator {
     .then(batchNo => {
       return this._waterfallBatch(batchNo, migrations, direction)
     })
-    .then(() => this._freeLock())
```
Comment (dannyfritz) [inline src/migrate/index.js]: If you're using Bluebird, a passthrough such as `.tap` might be cleaner. Same thing though!
http://bluebirdjs.com/docs/api/tap.html

File: src/migrate/index.js [hunk 2]
```diff
@@ -196,7 +196,7 @@ export default class Migrator {
...
+    .then(retVal => this._freeLock().then(() => retVal))
```
Comment (dannyfritz) [inline src/migrate/index.js]: If you're using Bluebird, a passthrough such as .tap might be cleaner. Same thing though!
http://bluebirdjs.com/docs/api/tap.html

Comment (elhigu) [inline src/migrate/index.js]: I was thinking about it, but noticed that I cannot use `.tap` since if it throws an error control won't go to catch block in promise chain. 

Other reason why I don't like to use it is that I prefer nowadays to use node's native promise since es6 has it now without need to import bluebird.

Comment (rhys-vdw) [inline src/migrate/index.js]: > I was thinking about it, but noticed that I cannot use .tap since if it throws an error control won't go to catch block in promise chain (as far as I know).

FYI This is the not the case. `tap` would be fine.
