### PR TITLE
Fix transaction support for migrations

### LINKED ISSUE #3063: Migrations can no longer be run from within a transaction
# Environment

Knex version: 0.16.0+
Database + version: Postgres 9.6.12
OS: MacOS 10.13

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**

Since version 0.16.0, migrations can no longer be run within a transaction. My team is currently using this behavior to stand up a database for running automated tests, and reverting to a clean database by rolling back the transaction after all testing is complete.

Minimal example:

```javascript
const conn = require('knex')(...);
conn.transaction((txn) => {
  txn.migrate.latest();
});
```

**2. Error message**

`Cannot set user params on a transaction - it can only inherit params from main knex instance`

**3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.**

Example (including docker postgres setup): https://github.com/jeffkenney/knex-txn-issue

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #3063

### CODE REVIEW

**Comment by kibertoad** [comment]
This fix makes an assumption that we had a pretty good reason why we don't want to modify or clone transaction instances, hence we are only ensuring that they work as much as they used before. If it is OK to modify or clone transaction instances, better solution could be implemented.

File: src/migrate/Migrator.js [hunk 1]
```diff
@@ -49,12 +49,16 @@ export default class Migrator {
   constructor(knex) {
     // Clone knex instance and remove post-processing that is unnecessary for internal queries from a cloned config
     if (isFunction(knex)) {
-      this.knex = knex.withUserParams({
-        ...knex.userParams,
-      });
-      this.knex.disableProcessing();
```
Comment (kibertoad) [inline src/migrate/Migrator.js]: Moved this inside operations instead to ensure correct state before each of them, regardless of how previous ones ended.
